### ISSUE TITLE
Public builds

### ISSUE THREAD

**Issue by dangranos** [anilsingh1605/android_device_samsung_logan2g#1]
Is there any chance to get public builds when/if this will build and work correctly?

**Comment by anilsingh1605** [comment]
Yes. We have successfully made CM to boot using this tree. We are now trying to fix other issues now.

**Comment by dangranos** [comment]
So far i haven't seen any releases (sorry if that sounds rude). When they are planned roughly?

**Comment by anilsingh1605** [comment]
The reason for not releasing is that there are RIL issues in CM 10.1. So, I decided to move on to CM 11.0.
Join this group for updates on CM: https://www.facebook.com/groups/GTS7262/
